### PR TITLE
feat: support redis-cluster topologySpreadConstraints(# 868)

### PR DESCRIPTION
**Pull request by xiaozhuang-a**
**Description**

support redis-cluster topologySpreadConstraints(# #868)

Fixes #ISSUE

**Type of change**

* New feature (non-breaking change which adds functionality)

**Checklist**

- [ ] Tests have been added/modified and all tests pass.
- [ ] Functionality/bugs have been confirmed to be unchanged or fixed.
- [x] I have performed a self-review of my own code.
- [ ] Documentation has been updated or added where necessary.

**Additional Context**

### CODE REVIEW

**Comment by drivebyer** [comment]
@xiaozhuang-a  some pipeline failed :)

**Comment by xiaozhuang-a** [comment]
> @xiaozhuang-a some pipeline failed :)

done

**Comment by xiaozhuang-a** [comment]
> @xiaozhuang-a  some pipeline failed :)

have a test failed，Where did this go wrong，I didn't find it

**Comment by xiaozhuang-a** [comment]
> @xiaozhuang-a  some pipeline failed :)

it's ok

**Review by drivebyer — APPROVED** [review]
lgtm

**Pull request merged**
