### PR TITLE
feat: redis-cluster add podAntiAffinity(#1174 )

### PR DESCRIPTION
**Pull request by xiaozhuang-a**
**Description**

support leader and follower anti affinity of pods with the same order

Fixes #ISSUE

**Type of change**

* New feature (non-breaking change which adds functionality)

**Checklist**

- [ ] Tests have been added/modified and all tests pass.
- [ ] Functionality/bugs have been confirmed to be unchanged or fixed.
- [x] I have performed a self-review of my own code.
- [ ] Documentation has been updated or added where necessary.

**Additional Context**

### CODE REVIEW

**Comment by drivebyer** [comment]
Nice idea. 

How aboud trigger mutation by adding an annotation to the RedisCluster resource, such as rediscluster.redis.redis.opstreelabs.in/role-anti-affinity. @xiaozhuang-a

**Comment by drivebyer** [comment]
BTW, we need add some test case to it.

**Comment by xiaozhuang-a** [comment]
> Nice idea.
> 
> How about trigger mutation by adding an annotation to the RedisCluster resource, such as rediscluster.redis.redis.opstreelabs.in/role-anti-affinity. @xiaozhuang-a

I think the 'add annotation' solution is very good, and I will implement it

**Comment by xiaozhuang-a** [comment]
> BTW, we need add some test case to it.

get

**Review by drivebyer — APPROVED** [review]
lgtm

**Comment by radsto** [comment]
Hi, could you please give us a hint on how you generated the certificate for the webhook `webhook-server-cert` ?

**Comment by xiaozhuang-a** [comment]
> Hi, could you please give us a hint on how you generated the certificate for the webhook `webhook-server-cert` ?

reference https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/charts/redis-operator/values.yaml

**Comment by xiaozhuang-a** [comment]
> Hi, could you please give us a hint on how you generated the certificate for the webhook `webhook-server-cert` ?

If you want to use this feature, just use this chart and set [the](https://github.com/OT-CONTAINER-KIT/redis-operator/blob/c32cd415a11bf5bd35fcf972b8a60b42ce1759ed/charts/redis-operator/values.yaml#L21)  to true

**Comment by radsto** [comment]
@xiaozhuang-a thank you I have managed to do it.

**Pull request merged**
