### PR TITLE
[BugFix] fix panic with redisExporter enabled

### PR DESCRIPTION
**Pull request by liortamari**
Signed-off-by: liortamary <lior.tamary@houzz.com>

### CODE REVIEW

**Comment by liortamari** [comment]
fixes https://github.com/OT-CONTAINER-KIT/redis-operator/issues/261

**Comment by liortamari** [comment]
@davidcollom / @iamabhishek-dubey 
I would appreciate your assistance here.
can you please review this one? 
and perhaps even issue a version release so we can use a new docker image with this resolved?

**Review by iamabhishek-dubey — APPROVED** [review]
LGTM

**Comment by liortamari** [comment]
@iamabhishek-dubey thanks for the fast response!
would it be possible to do a version release so we can get a docker image deployed instead of compiling our own?

**Pull request merged**
