### PR TITLE
Dependencies upgrade

### LINKED ISSUE #636: Update go version
**Describe the solution you'd like**

We have been using the go1.17 which is now quiet old we should upgrade the operator to the go1.21.
We should also consider upgrading these library : 

```
k8s.io/api v0.23.0
k8s.io/apimachinery v0.23.0
k8s.io/client-go v0.23.0
sigs.k8s.io/controller-runtime v0.11.0
```

**What version of redis-operator are you using?**

redis-operator version: v0.15.1

### PR DESCRIPTION
**Pull request by Azanul**
**Description**

Fixes #636 

**Type of change**

* New feature (non-breaking change which adds functionality)

**Checklist**

- [ ] Tests have been added/modified and all tests pass.
- [ ] Functionality/bugs have been confirmed to be unchanged or fixed.
- [ ] I have performed a self-review of my own code.
- [ ] Documentation has been updated or added where necessary.

### CODE REVIEW

**Comment by shubham-cmyk** [comment]
Looks like a lot of breaking change happened over here : https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.15.0

**Comment by Azanul** [comment]
> Looks like a lot of breaking change happened over here : https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.15.0

I apologize for not checking thoroughly, I mark the PR ready to review once the issues are addressed.

**Comment by shubham-cmyk** [comment]
@Azanul No issue this is a pretty typical one.

**Comment by shubham-cmyk** [comment]
update the go version from the workflow also 

https://github.com/OT-CONTAINER-KIT/redis-operator/blob/26f9c0be576c6fbcd263f322ac7bd38478aa8e5e/.github/workflows/operator-ci.yaml#L11

**Comment by Azanul** [comment]
@shubham-cmyk Should I also do the same for Dockerfile?

**Comment by shubham-cmyk** [comment]
> @shubham-cmyk Should I also do the same for Dockerfile?

Yes modify here [ FROM golang:1.17 as builder](https://github.com/OT-CONTAINER-KIT/redis-operator/blob/b5d1184db88cf16c96aac17b896d74096ddc827f/Dockerfile#L2C28-L2C28)

**Comment by Azanul** [comment]
@shubham-cmyk I think the failing CI job is an issue with golangci-lint. I see that there's an open PR #653 moving from manual install to gh-actions, would you consider upgrading it's version as well?

**Comment by shubham-cmyk** [comment]
@Azanul Rebase the master branch onto this branch. 
I have merged the CI lint

**Comment by Azanul** [comment]
> @Azanul Rebase the master branch onto this branch. I have merged the CI lint

Done. Please approve the workflows.

**Comment by shubham-cmyk** [comment]
@Azanul 

All right seems like we have passed `CI / code_quality_golang_ci_lint`.
I have to run a few more checks and further I could merge this.

**Review by shubham-cmyk — APPROVED** [review]
LGTM

**Pull request merged**
