### PR TITLE
Pass through Annotations and Labels to all Child resources

### PR DESCRIPTION
**Pull request by davidcollom**
This is an initial WIP to address the requests in #95

During testing, I'm seeing a lot of Satefulset updates failing, presumingly about some other immutable fields... I will do some more investigation in the coming days.

# Breaking Change:

Whilst implementing this feature, It felt as though the hard-coded Prometheus annotations felt right.
With this change, you MUST provide them to the `Redis`/`RedisCluster` resource to enable.

### CODE REVIEW

**Comment by davidcollom** [comment]
@iamabhishek-dubey  This should no longer be classed as WIP and is Ready for Review

**Review by iamabhishek-dubey — APPROVED** [review]

**Comment by iamabhishek-dubey** [comment]
@davidcollom can you please fix this conflict? otherwise this looks good

**Comment by oliveratprimer** [comment]
Thank you @davidcollom and everyone involved!

**Comment by blbradley** [comment]
can someone give an example of usage? i've tried the `Redis` resource, key `metadata.annotations` but my pod is not restarting with the annotations set

**Comment by liortamari** [comment]
@blbradley did you get this to work? I am also trying without luck so far.

**Pull request merged**
