### PR TITLE
[Bug] Fix the call of func checkAttachedSlave for 1 Master Replication

### PR DESCRIPTION
**Pull request by shubham-cmyk**
**Description**

Fixes https://github.com/OT-CONTAINER-KIT/redis-operator/issues/521

### CODE REVIEW

**Comment by abdul90082** [comment]
@shubham-cmyk May I know when we expect the next release to fix this issue?

**Comment by phlegx** [comment]
Hi there!

Could we release this feature? Would be awesome!

thanks!

**Comment by abdul90082** [comment]
@shubham-cmyk I am writing to report an issue I have encountered while using the latest release of [redis-operator:0.15.0] on Playground3. I have successfully tested the same configuration on Playground1 and Playground2 without issues.

The problem I am facing revolves around the **podSecurityContext** feature. In Playground3, when I attempt to utilize the podSecurityContext functionality as intended, I am encountering the following error:


**Error: error validating "": error validating data: ValidationError(RedisReplication.spec): unknown field "podSecurityContext" in in.opstreelabs.redis.redis.v1beta1.RedisReplication.spec**

If this is indeed a bug or compatibility issue, I kindly request your assistance in creating a GitHub issue for tracking purposes. This would not only help me but also contribute to the overall improvement of **Redis-Operator.**

Redis version : 0.15.0
Redis sentinel chat version : 0.15.3
Redis replication chart version : 0.15.3

**Comment by shubham-cmyk** [comment]
I would like to inspect that can you run 
`kubectl explain redisreplication.spec`
and give me a screen shot here the problem is helm upgrade doesn't change the scheme so you have to to that by deleting the crd and creating again. 

This is due to the backward in compatibility but I have raised a PR to support that. 
For now can you share the result of kubectl

**Comment by abdul90082** [comment]
Thank you for your message. I appreciate your effort in raising a PR to address the backward incompatibility issue. It's great to see your commitment to improving the project's compatibility.

In regards to your request, here's the result of the kubectl command you've asked for:
Screenshot from 2023-08-25 20-50-30

If you need any further assistance or if there's additional information you'd like to provide, please feel free to share. I'm here to help!

**Comment by shubham-cmyk** [comment]
I see there is no field named `podSecurityContext` here this is because the crd are not updated here. 
Can you please delete the operator and install the operator again that way the CRD would get updated.

**Comment by shubham-cmyk** [comment]
The PR is almost ready and would be merged with a release of v0.15.1 that could support both versions v0.14.0 and v0.15.0

**Pull request merged**
