### PR TITLE
[Feature]: Add InitContainer Field

### PR DESCRIPTION
**Pull request by drivebyer**
**Description**

Add initcontainer field in cr.

Init container can do task before redis startup, such as recover task. In init container, we can share volume with redis container and prepare data volume(backup set from remote S3) for it.

Fixes #ISSUE

**Type of change**

* New feature (non-breaking change which adds functionality)

**Checklist**

- [x] Testing has been performed
- [x] No functionality is broken
- [ ] Documentation updated

### CODE REVIEW

**Comment by drivebyer** [comment]
PTAL @shubham-cmyk  @iamabhishek-dubey

**Comment by shubham-cmyk** [comment]
It's a good idea to have an init Container for the restoration; even I was thinking the same. But we don't need here a complete container in the CR but a minimum required field. 


Here is some reference to the sidecar that we can launch
image

**Comment by shubham-cmyk** [comment]
Restore and backup bash script is on the to-do list and I would be added in the next release.

**Comment by drivebyer** [comment]
> But we don't need here a complete container in the CR but a minimum required field.

Fixed according to suggestion.

**Review by shubham-cmyk — COMMENTED** [review]
Update the initContainer

**Review by shubham-cmyk — COMMENTED** [review]
update : name init Container

**Pull request merged**
