### PR TITLE
[Feature] Add additional volume mounts for sentinel

### LINKED ISSUE #432: Add additional volume mounts for sentinel
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**What version of redis-operator are you using?**

redis-operator version: v0.14.0

**Additional context**

### LINKED ISSUE #434: Sentinel's label association is incorrect
**What version of redis operator are you using?**

```shell
# kubectl get svc sentinel-sentinel -o template='{{.spec.selector}}'
map[app:sentinel-sentinel redis_setup_type:cluster role:sentinel]

# kubectl get sts sentinel-sentinel -o template='{{.spec.selector}}'
map[matchLabels:map[app:sentinel redis_setup_type:cluster role:sentinel]]
```

redis-operator version: v0.14.0

**Does this issue reproduce with the latest release?**

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

### LINKED ISSUE #435: Sentinel's Service Ports association is incorrect
**What version of redis operator are you using?**

```shell
# kubectl get svc sentinel-sentinel -o template='{{.spec.ports}}'
[map[name:redis-client port:6379 protocol:TCP targetPort:6379] map[name:redis-exporter port:9121 protocol:TCP targetPort:9121]]
```

redis-operator version: v0.14.0

**Does this issue reproduce with the latest release?**

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

### LINKED ISSUE #438: PVC name repeated too long
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**What version of redis-operator are you using?**

redis-operator version: v0.14.0

**Additional context**

cr.Name: `test-cluster`
```yaml
pvcName:
  Origin: test-cluster-follower-test-cluster-follower-0
  Improved: data-test-cluster-follower-0
```

### PR DESCRIPTION
**Pull request by muicoder**
**Description**

**Type of change**

* Bug fix (non-breaking change which fixes an issue)
* New feature (non-breaking change which adds functionality)

**Checklist**

- [x] Testing has been performed
- [x] No functionality is broken
- [ ] Documentation updated

### CODE REVIEW

**Comment by muicoder** [comment]
Install Helm Chart for Standalone/Cluster/Replication/Sentinel
===
```shell
helm install redis ./chart --set mode=standalone
kubectl delete secrets sh.helm.release.v1.dev.v1

helm install redis ./chart --set mode=cluster
kubectl delete secrets sh.helm.release.v1.dev.v1

helm install redis ./chart --set mode=replication
kubectl delete secrets sh.helm.release.v1.dev.v1

helm install redis ./chart --set mode=sentinel --set repl=replication
kubectl delete secrets sh.helm.release.v1.dev.v1
```
Installed for Kubernetes v1.22.17
===
```shell
root@sealos001:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2022-12-08T11:47:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2022-12-08T11:42:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
root@sealos001:~# kubectl get pods
NAME                 READY   STATUS    RESTARTS   AGE
cluster-follower-0   2/2     Running   0          8m18s
cluster-follower-1   2/2     Running   0          8m5s
cluster-follower-2   2/2     Running   0          7m53s
cluster-leader-0     2/2     Running   0          9m
cluster-leader-1     2/2     Running   0          8m47s
cluster-leader-2     2/2     Running   0          8m31s
redis-sentinel-0     1/1     Running   0          7m45s
redis-sentinel-1     1/1     Running   0          7m42s
redis-sentinel-2     1/1     Running   0          7m35s
replication-0        2/2     Running   0          8m50s
replication-1        2/2     Running   0          8m36s
replication-2        2/2     Running   0          8m24s
standalone-0         2/2     Running   0          9m13s
root@sealos001:~# kubectl get pvc
NAME                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
data-cluster-follower-0   Bound    pvc-685d5427-2e91-45dd-a4d6-b254171a032b   50Gi       RWO            local-path-retain   8m38s
data-cluster-follower-1   Bound    pvc-7e8a3d7f-e2e5-42af-ae41-8a801700f295   50Gi       RWO            local-path-retain   8m25s
data-cluster-follower-2   Bound    pvc-ba151d21-b093-4699-bfac-ac0fe0bd547c   50Gi       RWO            local-path-retain   8m13s
data-cluster-leader-0     Bound    pvc-730a3ef6-bfd6-4306-b85f-74d2c644cb5d   50Gi       RWO            local-path-retain   9m20s
data-cluster-leader-1     Bound    pvc-7822ec30-8ea4-4ba7-907e-c5cb34ee8322   50Gi       RWO            local-path-retain   9m7s
data-cluster-leader-2     Bound    pvc-88cbce3a-cbf3-42d1-bb2b-d40bcdfb404e   50Gi       RWO            local-path-retain   8m51s
data-replication-0        Bound    pvc-a8894da8-b5e7-4531-bec4-7e5d5cccb593   50Gi       RWO            local-path-retain   9m10s
data-replication-1        Bound    pvc-e3cb864a-2e9f-4148-9508-53566c2349ab   50Gi       RWO            local-path-retain   8m56s
data-replication-2        Bound    pvc-edfea552-937e-4ca2-aef5-0347a3f0f17b   50Gi       RWO            local-path-retain   8m44s
data-standalone-0         Bound    pvc-a3dd4970-bf06-4331-a2aa-9d2ef5589123   50Gi       RWO            local-path-retain   9m33s
root@sealos001:~# kubectl get svc
NAME                          TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)              AGE
cluster-follower              ClusterIP   10.96.0.177   <none>        6379/TCP,9121/TCP    8m40s
cluster-follower-additional   ClusterIP   10.96.0.199   <none>        6379/TCP             8m40s
cluster-follower-headless     ClusterIP   None          <none>        6379/TCP             8m40s
cluster-leader                ClusterIP   10.96.1.215   <none>        6379/TCP,9121/TCP    9m22s
cluster-leader-additional     ClusterIP   10.96.0.208   <none>        6379/TCP             9m22s
cluster-leader-headless       ClusterIP   None          <none>        6379/TCP             9m22s
kubernetes                    ClusterIP   10.96.0.1     <none>        443/TCP              34h
redis-sentinel                ClusterIP   10.96.2.19    <none>        26379/TCP,9121/TCP   9m5s
redis-sentinel-additional     ClusterIP   10.96.3.217   <none>        26379/TCP            9m5s
redis-sentinel-headless       ClusterIP   None          <none>        26379/TCP            9m5s
replication                   ClusterIP   10.96.3.5     <none>        6379/TCP,9121/TCP    9m12s
replication-additional        ClusterIP   10.96.3.153   <none>        6379/TCP             9m12s
replication-headless          ClusterIP   None          <none>        6379/TCP             9m12s
standalone                    ClusterIP   10.96.0.114   <none>        6379/TCP,9121/TCP    9m35s
standalone-additional         ClusterIP   10.96.1.21    <none>        6379/TCP             9m35s
standalone-headless           ClusterIP   None          <none>        6379/TCP             9m35s
root@sealos001:~# kubectl get secret
NAME                          TYPE                                  DATA   AGE
auth.cluster                  Opaque                                1      9m26s
auth.replication              Opaque                                1      9m16s
auth.standalone               Opaque                                1      9m39s
root@sealos001:~# kubectl get cm
NAME                 DATA   AGE
config.cluster       4      9m26s
config.replication   3      9m16s
config.sentinel      3      9m39s
config.standalone    3      9m10s
```

**Comment by muicoder** [comment]
> 
### Kill replication-0 (master), logs for replication-sentinel-0.
```shell
1:X 19 Feb 2023 03:22:00.495 # +elected-leader master myMaster 10.0.1.60 6379                                                                                                         
1:X 19 Feb 2023 03:22:00.495 # +failover-state-select-slave master myMaster 10.0.1.60 6379                                                                                            
1:X 19 Feb 2023 03:22:00.579 # +selected-slave slave 10.0.0.36:6379 10.0.0.36 6379 @ myMaster 10.0.1.60 6379                                                                          
1:X 19 Feb 2023 03:22:00.579 * +failover-state-send-slaveof-noone slave 10.0.0.36:6379 10.0.0.36 6379 @ myMaster 10.0.1.60 6379                                                       
1:X 19 Feb 2023 03:22:00.680 * +failover-state-wait-promotion slave 10.0.0.36:6379 10.0.0.36 6379 @ myMaster 10.0.1.60 6379                                                           
1:X 19 Feb 2023 03:22:01.467 # +promoted-slave slave 10.0.0.36:6379 10.0.0.36 6379 @ myMaster 10.0.1.60 6379                                                                          
1:X 19 Feb 2023 03:22:01.467 # +failover-state-reconf-slaves master myMaster 10.0.1.60 6379                                                                                           
1:X 19 Feb 2023 03:22:01.559 * +slave-reconf-sent slave 10.0.1.163:6379 10.0.1.163 6379 @ myMaster 10.0.1.60 6379                                                                     
1:X 19 Feb 2023 03:22:02.505 * +slave-reconf-inprog slave 10.0.1.163:6379 10.0.1.163 6379 @ myMaster 10.0.1.60 6379                                                                   
1:X 19 Feb 2023 03:22:02.505 * +slave-reconf-done slave 10.0.1.163:6379 10.0.1.163 6379 @ myMaster 10.0.1.60 6379                                                                     1:X 19 Feb 2023 03:22:02.582 # -odown master myMaster 10.0.1.60 6379                                                                                                                  
1:X 19 Feb 2023 03:22:02.582 # +failover-end master myMaster 10.0.1.60 6379                                                                                                           1:X 19 Feb 2023 03:22:02.582 # +switch-master myMaster 10.0.1.60 6379 10.0.0.36 6379                                                                                                  
1:X 19 Feb 2023 03:22:02.582 * +slave slave 10.0.1.163:6379 10.0.1.163 6379 @ myMaster 10.0.0.36 6379                                                                                 
1:X 19 Feb 2023 03:22:02.582 * +slave slave 10.0.1.60:6379 10.0.1.60 6379 @ myMaster 10.0.0.36 6379                                                                                   
1:X 19 Feb 2023 03:22:03.593 # +sdown slave 10.0.1.60:6379 10.0.1.60 6379 @ myMaster 10.0.0.36 6379                                                                                   
1:X 19 Feb 2023 03:23:05.275 * +slave slave 10.0.1.207:6379 10.0.1.207 6379 @ myMaster 10.0.0.36 6379
```

**Comment by shubham-cmyk** [comment]
@muicoder Why do we need attached volume at sentinel

**Comment by muicoder** [comment]
> @muicoder Why do we need attached volume at sentinel 

Support official redis images, and overwrite entrypoint.sh by mounting configmap.

**Comment by muicoder** [comment]
The script has been improved with sh instead of bash to support the official alpine image.

https://github.com/muicoder/redis-operator/blob/action/chart/files/entrypoint.sh

**Comment by shubham-cmyk** [comment]
@muicoder I would merge this 2 PR on an immediate basis Otherwise I you would like can I do it?
https://github.com/OT-CONTAINER-KIT/redis-operator/issues/441
https://github.com/OT-CONTAINER-KIT/redis-operator/issues/435

**Comment by muicoder** [comment]
@shubham-cmyk Please check

**Comment by muicoder** [comment]
@shubham-cmyk Can you merge?

**Comment by shubham-cmyk** [comment]
@muicoder 
Do we need PV with the sentinel mode also ?

**Comment by muicoder** [comment]
> @muicoder 
> Do we need PV with the sentinel mode also ? 

Support overwrite entrypoint.sh by mounting configmap.

**Pull request closed without merging**
