### PR TITLE
feat: add redisreplication status masterNode

### PR DESCRIPTION
**Pull request by drivebyer**
**Description**

Add redisreplication status masterNode

**Type of change**

* Bug fix (non-breaking change which fixes an issue)
* New feature (non-breaking change which adds functionality)
* Breaking change (fix or feature that would cause existing functionality to not work as expected)

**Checklist**

- [x] Tests have been added/modified and all tests pass.
- [x] Functionality/bugs have been confirmed to be unchanged or fixed.
- [x] I have performed a self-review of my own code.
- [ ] Documentation has been updated or added where necessary.

**Additional Context**

### CODE REVIEW

**Comment by wkd-woo** [comment]
Hello @drivebyer :) !!!
Could it be a function of the same purpose as the Pull Request I previously requested? #785

**Comment by drivebyer** [comment]
@wkd-woo At first glance, they may seem identical, but they actually serve different purposes. With this pull request, we can obtain the conclusion status from a custom resource without having to delve into the details of the pod.

**Comment by wkd-woo** [comment]
Thank you for your response! @drivebyer 
Actually, there were some problems with the features I added.

As you said, the feature I requested was a workflow in the form of diving in and out of the pod, so it took a lot of time for reconcilers to update the "master" label after failover (about 1 minute)

This was too fatal to be applied in a production environment in reality. It means that HA outages take more than a minute to access a single endpoint as a service.

It would be great if this PR merges. Thanks!


*I have an additional question, I'm not a k8s expert, so I'm asking, then is it possible to access master/slave from outside the cluster as a single endpoint through service?

**Comment by shubham-cmyk** [comment]
@drivebyer can we try some failover testing here and check who is the master now

**Comment by drivebyer** [comment]
> @drivebyer can we try some failover testing here and check who is the master now

Sure

**Comment by drivebyer** [comment]
> It would be great if this PR merges. Thanks!

I would review it.

**Comment by drivebyer** [comment]
@shubham-cmyk, I tested it on my local k8s setup. The status gets updated to the new master once the old master pod is killed.

**Review by shubham-cmyk — APPROVED** [review]
LGTM

**Pull request merged**
