### PR TITLE
[Feature] Add RedisExporter for sentinel

### PR DESCRIPTION
**Pull request by muicoder**
Signed-off-by: muicoder <muicoder@gmail.com>

**Description**

Feature: Add RedisExporter for sentinel

**Type of change**

* Bug fix (non-breaking change which fixes an issue)
* New feature (non-breaking change which adds functionality)
* Breaking change (fix or feature that would cause existing functionality to not work as expected)

**Checklist**

- [x] Testing has been performed
- [x] No functionality is broken
- [ ] Documentation updated

### CODE REVIEW

**Comment by muicoder** [comment]
merge to #439

**Comment by shubham-cmyk** [comment]
@iamabhishek-dubey  Merge

**Comment by muicoder** [comment]
@shubham-cmyk Please check

**Comment by genofire** [comment]
Any update on Review/Merge ?

**Comment by shubham-cmyk** [comment]
@genofire There is a linting issue which we are facing in the repository
So before any merge, the linting should be resolved. I am working on that issue this week.

**Comment by shubham-cmyk** [comment]
CRD updated at : 

https://github.com/OT-CONTAINER-KIT/redis-operator/pull/482

**Pull request merged**
