### PR TITLE
Add - GithubAction For Incoming e2e Test Case

### PR DESCRIPTION
**Pull request by drivebyer**
Adding GithubAction that would test the redis-operator image on the kind cluster

### CODE REVIEW

**Comment by shubham-cmyk** [comment]
@drivebyer It is not failing due to that. We have to make a proper KIND related setup. I have tested it on a live cluster it was working there. KIND setup is what I need to achieve. 

I would push some changes regards that

**Comment by drivebyer** [comment]
> 

OK

**Comment by shubham-cmyk** [comment]
@drivebyer For this change we should not use the helm chart for deploying the operator instead we should build the operator right from scratch( Dockerfile )  from here and install it. 

We could look how the make install would work here

**Comment by drivebyer** [comment]
> @drivebyer For this change we should not use the helm chart for deploying the operator instead we should build the operator right from scratch( Dockerfile ) from here and install it.
> 
> We could look how the make install would work here

Yes, I am testing now. I could build image on runner, then use `kind load` load the fresh operator image to kind nodes.

**Pull request closed without merging**
