### PR TITLE
fix: redis-cluster unexpected downscaling (#1167)

### LINKED ISSUE #1167: crash master after failover can cause unexpected downscaling
**What version of redis operator are you using?**

```shell
kubectl logs <_redis-operator_pod_name> -n <namespace>
```

redis-operator version: v0.18.1

**Does this issue reproduce with the latest release?**

yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**

**What did you expect to see?**

cluster failure will not cause expansion or contraction of capacity

**What did you see instead?**
after the failover, the status of the original faulty master in the cluster nodes will be 'master fail', which will trigger downscaling

### PR DESCRIPTION
**Pull request by xiaozhuang-a**
**Description**

1. ensure statefulset status is ready before scaling
2. failover command is not effective
3. return directly after failover command

Fixes #1167 

**Type of change**

* Bug fix (non-breaking change which fixes an issue)
* 
**Checklist**

- [ ] Tests have been added/modified and all tests pass.
- [ ] Functionality/bugs have been confirmed to be unchanged or fixed.
- [x] I have performed a self-review of my own code.
- [ ] Documentation has been updated or added where necessary.

**Additional Context**

### CODE REVIEW

**Comment by xiaozhuang-a** [comment]
already self-test passed

**Comment by drivebyer** [comment]
@xiaozhuang-a  please fix the failed check :)

**Comment by drivebyer** [comment]
We should retain the content from [this commit](https://github.com/OT-CONTAINER-KIT/redis-operator/commit/cda99a4c01c002b2d9ee2be141c053e4b821f506) in this PR. It seems the content was removed after resolving the conflict. @xiaozhuang-a

**Comment by xiaozhuang-a** [comment]
> We should retain the content from [this commit](https://github.com/OT-CONTAINER-KIT/redis-operator/commit/cda99a4c01c002b2d9ee2be141c053e4b821f506) in this PR. It seems the content was removed after resolving the conflict. @xiaozhuang-a

there are some issues with conflict merging, please allow me to bring up a new PR

**Comment by xiaozhuang-a** [comment]
> We should retain the content from [this commit](https://github.com/OT-CONTAINER-KIT/redis-operator/commit/cda99a4c01c002b2d9ee2be141c053e4b821f506) in this PR. It seems the content was removed after resolving the conflict. @xiaozhuang-a

https://github.com/OT-CONTAINER-KIT/redis-operator/pull/1173

**Pull request closed without merging**
