### PR TITLE
test: add envtest for redis standalone

### LINKED ISSUE #656: [Tracker] : Cover Testing of Operator.
Right now, this operator's Test coverage is low, making it difficult to test the incoming PR and breaking changes.  
This Issue is a Tracker for the incoming Test case that could be merged. 

The test case could be either of 

1. Unit test 
2. Integration test 
3. e2e Test  ( we would use kuttl for this ) [check](https://github.com/OT-CONTAINER-KIT/redis-operator/tree/master/tests) 

All the PRs related to the test should reference this issue. 

It would be an excellent approach to work on a few test functions at a time which make the PR a bit cleaner and easier to write. 

Read [this](https://www.infracloud.io/blogs/testing-kubernetes-operator-envtest/) for a quick start.

Worflow used : https://github.com/OT-CONTAINER-KIT/redis-operator/pull/661

### PR DESCRIPTION
**Pull request by MathieuCesbron**
**Description**

I feel like it would be a good idea to add integration tests with EnvTest on the reconcile loop [like mentioned here](https://www.infracloud.io/blogs/testing-kubernetes-operator-envtest/).

Would this feature be accepted if I make it ?

_Edit: Feature accepted_

Fixes #656

**Type of change**

* Bug fix (non-breaking change which fixes an issue)

**Checklist**

- [x] Tests have been added/modified and all tests pass.
- [x] Functionality/bugs have been confirmed to be unchanged or fixed.
- [x] I have performed a self-review of my own code.
- [x] Documentation has been updated or added where necessary.

### CODE REVIEW

**Comment by drivebyer** [comment]
Actually, we use chainsaw to do some e2e test, plz see https://github.com/OT-CONTAINER-KIT/redis-operator/tree/master/tests/e2e-chainsaw/v1beta2.

**Comment by MathieuCesbron** [comment]
So you think there is no point in doing integration test ? e2e is enough ? 

I like integration tests because it's still fast to run and still test the reconcile logic in an holistic way.

**Comment by drivebyer** [comment]
> So you think there is no point in doing integration test ? e2e is enough ?
> 
> I like integration tests because it's fast to run while still testing the reconcile logic in an holistic way.

Integration tests is nice of course.

**Comment by MathieuCesbron** [comment]
Thanks for your input.

I asked because I would like to know if I should start the feature or if it's not gonna be accepted anyway.

**Comment by drivebyer** [comment]
> Thanks for your input.
> 
> I asked because I would like to know if I should start the feature or if it's not gonna be accepted anyway.

IMO, it's a nice feature for the operator.

**Comment by MathieuCesbron** [comment]
I have added the setup for integration test and integration tests for redis standalone. We check that statefulset, service,... are created and that deleting the CR delete the statefulset.

I will add integration tests for the other redis (cluster, replication, sentinel) each in his own PR if you don't mind.

**Review by drivebyer — APPROVED** [review]
nice work!

**Pull request merged**
