### PR TITLE
add watchnamespace function

### PR DESCRIPTION
**Pull request by progmatv**
This PR add watchnamespace function. To activate it add to manager.yaml in section containers:

```
         env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
```

### CODE REVIEW

**Comment by shubham-cmyk** [comment]
I don't think there is a need for this PR. 
Since it is already included in the code. 

image

**Comment by shubham-cmyk** [comment]
This option is already included in the code. 
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/main.go#L77

**Comment by progmatv** [comment]
OLM requires `watchNamespace` as a variable name

**Comment by shubham-cmyk** [comment]
can we change the name of the env-variable here ?

**Comment by progmatv** [comment]
yes this can work

**Pull request merged**
