### PR TITLE
Optimize pvcTemplate Name for Storage #438

### LINKED ISSUE #438: PVC name repeated too long
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**What version of redis-operator are you using?**

redis-operator version: v0.14.0

**Additional context**

cr.Name: `test-cluster`
```yaml
pvcName:
  Origin: test-cluster-follower-test-cluster-follower-0
  Improved: data-test-cluster-follower-0
```

### PR DESCRIPTION
**Pull request by muicoder**
**Description**

Fixes #438 

**Type of change**

* Bug fix (non-breaking change which fixes an issue)
* New feature (non-breaking change which adds functionality)
* Breaking change (fix or feature that would cause existing functionality to not work as expected)

**Checklist**

- [x] Testing has been performed
- [x] No functionality is broken
- [ ] Documentation updated

### CODE REVIEW

**Comment by muicoder** [comment]
#438

**Comment by shubham-cmyk** [comment]
LGTM!

**Comment by shubham-cmyk** [comment]
@iamabhishek-dubey  Merge!

**Review by iamabhishek-dubey — APPROVED** [review]

**Comment by chobostar** [comment]
@iamabhishek-dubey  @shubham-cmyk 

>>Bug fix (non-breaking change which fixes an issue)

This actually breaking change, we got an error: https://github.com/OT-CONTAINER-KIT/redis-operator/issues/507

I'm wonder Is it possible to revert this change? (please)

**Pull request merged**
