### PR TITLE
feat: add readiness/liveness probe to redis operator chart

### LINKED ISSUE #974: Enable readinessProbe on redis-operator deployment
**Is your feature request related to a problem? Please describe.**

Analyzing helm chart for redis-operator with kube-score, fails on Pod Probes

**Describe the solution you'd like**

Enable configuration for readinesProbe if possible technically.

**Describe alternatives you've considered**

**What version of redis-operator are you using?**

redis-operator version: 0.16.2 (helm chart)

**Additional context**

Failure from kube-score
[CRITICAL] Pod Probes
        · Container is missing a readinessProbe
            A readinessProbe should be used to indicate when the service is
            ready to receive traffic. Without it, the Pod is risking to receive
            traffic before it has booted. It's also used during rollouts, and
            can prevent downtime if a new version of the application is failing.
            More information: https://github.com/zegl/kube-score/blob/master/README_PROBES.md

### PR DESCRIPTION
**Pull request by drivebyer**
**Description**

Fixes #974

**Type of change**

* New feature (non-breaking change which adds functionality)

**Checklist**

- [ ] Tests have been added/modified and all tests pass.
- [ ] Functionality/bugs have been confirmed to be unchanged or fixed.
- [ ] I have performed a self-review of my own code.
- [ ] Documentation has been updated or added where necessary.

**Additional Context**

### CODE REVIEW

**Comment by zifeo** [comment]
@drivebyer this seems to be invalid as probes requires a handler: can you confirm your intent?

**Comment by arcdigital** [comment]
can't deploy with webhook enabled, due to this it seems.

> Error: 1 error occurred:
        * Deployment.apps "redis-operator" is invalid: [spec.template.spec.containers[0].livenessProbe: Required value: must specify a handler type, spec.template.spec.containers[0].readinessProbe: Required value: must specify a handler type]

```
redisOperator:
  webhook: true
```

**Comment by drivebyer** [comment]
@zifeo @arcdigital Thank you for pointing this out. It has been resolved through [this pull request](https://github.com/OT-CONTAINER-KIT/redis-operator/pull/1121).

**Comment by zifeo** [comment]
@drivebyer thanks for the quick fix!

**Pull request merged**
