### PR TITLE
Adding TLS Secret Support

### PR DESCRIPTION
**Pull request by davidcollom**
Add ability to pass a TLS certificate to the stateful set, for example using Cert-Manager:

```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: sample-ca
spec:
  ca:
    secretName: sample-ca-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sample-ca
spec:
  isCA: true
  commonName: sample
  secretName: sample-ca-cert
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sample  # this name should match the one appeared in kustomizeconfig.yaml
spec:
  dnsNames:
  - sample-master.default.svc
  - sample-master.default.svc.cluster.local
  - sample-slave.default.svc
  - sample-slave.default.svc.cluster.local
  - sample-slave-0
  - sample-slave-1
  - sample-slave-2
  - sample-slave-3
  - sample-master-0
  - sample-master-1
  - sample-master-2
  - sample-master-3
  issuerRef:
    kind: Issuer
    name: sample-ca
    group: cert-manager.io
  secretName: sample-cert # this secret will not be prefixed, since it's not managed by kustomize
---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: sample
spec:
  mode: cluster
  size: 3
  global:
    image: quay.io/opstree/redis:v6.2
    imagePullPolicy: IfNotPresent
    existingPasswordSecret:
      name: redis-password
      key: password
    TLS:
      secret:
        secretName: sample-cert
        optional: false
```

Will result in a Redis instance using a SelfSigned TLS Certificate, stored in a kubernetes secret and available for any application to pick up and use.

N.B:
The Exporter is ignoring the validity of the certificates (but still using them), as I was unable to find a way to override the client-name within the exporter.

### CODE REVIEW

**Comment by iamabhishek-dubey** [comment]
Please fix merge conflict

**Review by fernandosierrap — APPROVED** [review]

**Comment by davidcollom** [comment]
@iamabhishek-dubey PR Updated and merge conflicts resolved.

**Comment by jpuskar** [comment]
This seems like the only big feature missing from this (awesome) operator.

**Comment by davidcollom** [comment]
@iamabhishek-dubey PR Updated and ready to merge/review

**Comment by iamabhishek-dubey** [comment]
@davidcollom PR looks good to me, can you create an example inside the example folder. So it would be easy for people to refer to it.

**Comment by davidcollom** [comment]
Sure, I thought I had, most will be included in this PR but I agree.. having them in the examples will help future users. 👍

**Comment by davidcollom** [comment]
@iamabhishek-dubey  - Please find examples added in 6952fb8b4e427bdf913aebebe531a61ac057c323

**Comment by iamabhishek-dubey** [comment]
Please fix the conflicts for this as well @davidcollom

**Comment by davidcollom** [comment]
Thanks for merging/accepting this pr @iamabhishek-dubey .. there's a supporting or required for the TLS portion in the docker image also @ https://github.com/OT-CONTAINER-KIT/redis/pull/8 which will need merging before this feature is complete.

**Comment by hufon** [comment]
Hi @davidcollom  it seems you inverted tls.key and tls.crt in https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/k8sutils/secrets.go#L57

**Comment by hufon** [comment]
@davidcollom i've opened a PR to try to get it working on redis cluster https://github.com/OT-CONTAINER-KIT/redis-operator/pull/255

**Pull request merged**
