### PR TITLE
[Feature] Add Redis Sentinel Support 

### PR DESCRIPTION
**Pull request by shubham-cmyk**
Redis Sentinel Mode Is now supported 
Add your redis-replication name to the field 

```
  redisSentinelConfig: 
    redisReplicationName : redis-replication
```

### CODE REVIEW

**Review by iamabhishek-dubey — APPROVED** [review]

**Comment by muicoder** [comment]
Error: initializing source docker://quay.io/opstree/redis-sentinel:v7.0.7: reading manifest v7.0.7 in quay.io/opstree/redis-sentinel: unauthorized: access to the requested resource is not authorized

**Comment by shubham-cmyk** [comment]
@muicoder We have not released helm we would do it today

**Comment by lapete** [comment]
Hi, I still can't pull the sentinel chart from quay.io nor find it in https://github.com/OT-CONTAINER-KIT/helm-charts/tree/main/charts  
Is it not released yet or am I doing something wrong?  
`Failed to pull image "quay.io/opstree/redis-sentinel:v7.0.7": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/opstree/redis-sentinel:v7.0.7": failed to resolve reference "quay.io/opstree/redis-sentinel:v7.0.7": pulling from host quay.io failed with status code [manifests v7.0.7]: 401 UNAUTHORIZED`
I'm on operator 0.14 and used the example code from this repo.

**Comment by muicoder** [comment]
> Hi, I still can't pull the sentinel chart from quay.io nor find it in https://github.com/OT-CONTAINER-KIT/helm-charts/tree/main/charts  
> Is it not released yet or am I doing something wrong?  
> `Failed to pull image "quay.io/opstree/redis-sentinel:v7.0.7": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/opstree/redis-sentinel:v7.0.7": failed to resolve reference "quay.io/opstree/redis-sentinel:v7.0.7": pulling from host quay.io failed with status code [manifests v7.0.7]: 401 UNAUTHORIZED`
> I'm on operator 0.14 and used the example code from this repo.

You can experience this chart first: #436

**Comment by shubham-cmyk** [comment]
@lapete Helm Chart were released

**Comment by lapete** [comment]
Thanks, I noticed already and am using it. :) Just waiting for the Exporter being merged now, I've seen there's a PR already

**Comment by shubham-cmyk** [comment]
It would be merged soon once the redis cluster scaling on runtime PR is merged.

**Comment by lapete** [comment]
That's great news, thanks for letting me know.

**Pull request merged**
