### PR TITLE
Fixes issue with arm64 support.

### LINKED ISSUE #390: arm64 support not working
Deploying redis operator on a arm64 linux machine (Ubuntu 20.04.4 LTS) not working with versions v0.13.0 and v0.13.0-arm64.

Both cause error:
`exec /manager: exec format error`

while using these images on amd machines does work.

kubectl version v1.25.0.

### PR DESCRIPTION
**Pull request by mprimeaux**
**Description**

This PR adds support for multi-architecture container images. I am not sure of the CI flow but rather than reusing the existing make targets (e.g. `docker-build`), I could create new make targets for the `docker builds` commands but wanted to get the conversation started before making any assumptions.

Fixes #390 

**Type of change**

* Bug fix (non-breaking change which fixes an issue)

**Checklist**

- [x] Testing has been performed
- [x] No functionality is broken
- [ ] Documentation updated

### CODE REVIEW

**Review by iamabhishek-dubey — APPROVED** [review]

**Comment by iamabhishek-dubey** [comment]
@mprimeaux can we make sure CI is passing?

**Comment by mprimeaux** [comment]
@iamabhishek-dubey Yes, of course. I will look into ensuring this passes.

**Comment by mprimeaux** [comment]
@iamabhishek-dubey Unless I am misreading [the error](https://dev.azure.com/opstreedevops/DevOps/_build/results?buildId=633&view=logs&j=fb28d394-761e-5016-79d3-904894ed24e2&t=b025c58d-a4fe-5d5b-db63-4297e3dae842), it appears this is a linting rule, which suggests not to use the `--platform flag with FROM`. However, this is needed when dealing with multi-architecture images. 

Arguably, use of the `--platform` flag could be relaxed for on [line 2](https://github.com/mprimeaux/redis-operator/blob/e4ba2d4f58e31c936c47e5cbe709adb1eebd287e/Dockerfile#L2) of the `Dockerfile` but not on [line 47](https://github.com/mprimeaux/redis-operator/blob/e4ba2d4f58e31c936c47e5cbe709adb1eebd287e/Dockerfile#L47) since we need to specify `$TARGETPLATFORM`.

Can we relax the linting rule?

**Comment by mprimeaux** [comment]
@iamabhishek-dubey It appears the issue experiencing in the above CI pipelines has been updated to not be a linting error as per [hadolint DL3029](https://github.com/hadolint/hadolint/issues/861). Fixed in release [2.9.1](https://github.com/hadolint/hadolint/releases/tag/v2.9.1).  

Can the CI pipeline be updated to use the [latest release](https://github.com/hadolint/hadolint/releases/tag/v2.12.0)?  I can't find mention of `hadolint` in this repository. Your help is appreciated.

**Comment by mprimeaux** [comment]
@iamabhishek-dubey I've added two PRs in the `k8s-vault-webhook` and `k8s-secret-injector` repositories as per above. I'm unable to verify if this addresses the CI pipeline here but hope you can shed some insights on it.

**Comment by iamabhishek-dubey** [comment]
@mprimeaux I have updated the hadolint version for this CI pipeline as well but I can see it is still failing

**Comment by mprimeaux** [comment]
@iamabhishek-dubey Thanks much. I am not sure about the pipeline failure, either. [Here](https://dev.azure.com/opstreedevops/DevOps/_build/results?buildId=633&view=logs&j=fb28d394-761e-5016-79d3-904894ed24e2&t=b025c58d-a4fe-5d5b-db63-4297e3dae842) is the specific log from [this](https://dev.azure.com/opstreedevops/DevOps/_build/results?buildId=633&view=results) pipeline.

You can see the failure **seems* to be coming from hadolint. What is interesting is these are the same two warnings as before. Are these warnings being treated as errors?

**Comment by iamabhishek-dubey** [comment]
I think it might be the case @mprimeaux

**Comment by mprimeaux** [comment]
@iamabhishek-dubey Rather than relaxing the container image file lint rule for [DL3029](https://github.com/hadolint/hadolint/wiki/DL3029), I removed the `--platform` flag.

**Comment by mprimeaux** [comment]
Note that to build the multi-architecture container images, you'll want to first run the `docker-create` make target before running `docker-build` or `bundle-build`.

**Review by iamabhishek-dubey — APPROVED** [review]

**Pull request merged**
